---
- name: HTTPS transport
  apt:
    name: apt-transport-https
    state: present 

- name: Add Docker Repo Key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9
    url: http://get.docker.io/gpg
    state: present

- name: Add Docker repository and update apt cache
  apt_repository:
    repo: deb https://get.docker.com/ubuntu docker main
    update_cache: yes
    state: present

- name: Install lxc-docker package
  apt:
    name: lxc-docker
    state: latest
    update_cache: yes
    cache_valid_time: 600

- user:
     name: conductr

- name: Non-root access
  command: usermod -a -G docker conductr
  become: yes
  become_method: sudo
    
- name: Restart docker
  service:
    name: docker
    state: restarted
  
