---
- name: Install add-apt-repostory
  apt: name=software-properties-common state=latest

- name: Add HAProxy Repository
  apt_repository: repo='ppa:vbernat/haproxy-1.5'

- name: Install HAProxy
  apt: name=haproxy state=latest

