---
- name: Install python 2.7
  raw: apt-get update -qq && apt-get install -qq python2.7

- name: create softlink for python 2.7
  raw: ln -s /usr/bin/python2.7 /usr/bin/python

- name: Ensure /srv/web exists
  file:
    path: /srv/web
    state: directory
    mode: 0755
    owner: "{{ REMOTE_USER }}"
