---
- name: Copy ConductR Agent
  synchronize: src=conductr/files/{{ CONDUCTR_AGENT_PKG }} dest={{ CONDUCTR_CORE_WORK_DIR }}

- name: Install ConductR Agent
  apt: deb={{ CONDUCTR_CORE_WORK_DIR }}/{{ CONDUCTR_AGENT_PKG }}

- command: rm {{ CONDUCTR_CORE_WORK_DIR }}/{{ CONDUCTR_AGENT_PKG }}

- service: name=conductr-agent state=stopped

- shell: 'echo -Dconductr.agent.ip=$(hostname -i)| sudo tee -a /usr/share/conductr-agent/conf/conductr-agent.ini'
  become: yes
  become_method: sudo

- shell: 'echo -Dakka.loglevel=debug | sudo tee -a /usr/share/conductr-agent/conf/conductr-agent.ini'
  become: yes
  become_method: sudo

- service: name=conductr-agent state=stopped

- command: rm -rf /usr/share/conductr-agent/conf/core-nodes
  become: yes
  become_method: sudo
  ignore_errors: yes