- name: Get instance id
  get_url: url=http://169.254.169.254/latest/meta-data/instance-id dest={{ REMOTE_WORK_DIR }}/instance-id.txt

- shell: "cat {{ REMOTE_WORK_DIR }}/instance-id.txt"
  register: instanceid

- debug: msg="Instance id -- {{ instanceid.stdout }}"

- name: Gather facts
  action: ec2_facts

- name: Register with ELB
  local_action:
    module: ec2_elb
    instance_id: "{{ instanceid.stdout }}"
    ec2_elbs: "{{ ELB }}"
    region: "{{ EC2_REGION }}"
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: present
